name: reseller-portal

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      PORT: ${API_PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
  postgres:
    image: postgres:17.2
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGPORT=${DB_PORT}